services:
  server:
    image: nyvek/site-novidadescripto
    build:
      context: .
    environment:
      - NEXT_PUBLIC_NEWS_URL="https://api.novidadescripto.com.br/news"
      - NEXT_PUBLIC_GOOGLE_ADS_CLIENT_ID="ca-pub-3646211809176894"
    ports:
      - 3000:3000