services:
  server:
    image: nyvek/site-novidadescripto
    build:
      context: .
    environment:
      - NEXT_PUBLIC_NEWS_URL="http://ec2-18-188-23-208.us-east-2.compute.amazonaws.com:3001/news"
    ports:
      - 3000:3000